spring.application.name=taskforge

# Server Port
server.port=8080

# MySQL DB
spring.datasource.url=jdbc:postgresql://ep-holy-wind-ansbmsyg-pooler.c-6.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_6aqJz5ZcfpIK&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_6aqJz5ZcfpIK&ssl
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true